"""create initial schema

Revision ID: d153c44ac21e
Revises: 
Create Date: 2026-09-18 22:27:06.874248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd153c44ac21e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('READER', 'LIBRARIAN', name='user_role'), server_default='READER', nullable=False),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'author_id')
    )
    op.create_table('book_copies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'BORROWED', 'LOST', 'DAMAGED', name='book_copy_status'), server_default='AVAILABLE', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('acquired_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_number')
    )
    op.create_index('ix_book_copies_book_id', 'book_copies', ['book_id'], unique=False)
    op.create_index('ix_book_copies_status', 'book_copies', ['status'], unique=False)
    op.create_table('book_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DUE_DATE_APPROACHING', 'BOOK_READY', 'RESERVATION_EXPIRED', 'OVERDUE', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'READY', 'FULFILLED', 'CANCELLED', 'EXPIRED', name='reservation_status'), server_default='WAITING', nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('expires_at IS NULL OR expires_at >= reserved_at', name='ck_reservations_expires_after_reserved'),
    sa.CheckConstraint('fulfilled_at IS NULL OR fulfilled_at >= reserved_at', name='ck_reservations_fulfilled_after_reserved'),
    sa.CheckConstraint('queue_position > 0', name='ck_reservations_queue_position_positive'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_book_id', 'reservations', ['book_id'], unique=False)
    op.create_index('ix_reservations_book_status_queue', 'reservations', ['book_id', 'status', 'queue_position'], unique=False)
    op.create_index('ix_reservations_status', 'reservations', ['status'], unique=False)
    op.create_index('ix_reservations_user_id', 'reservations', ['user_id'], unique=False)
    op.create_table('loans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('copy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('librarian_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETURNED', 'OVERDUE', name='loan_status'), server_default='ACTIVE', nullable=False),
    sa.CheckConstraint("\n            (\n                status = 'RETURNED'\n                AND returned_at IS NOT NULL\n            )\n            OR\n            (\n                status IN ('ACTIVE', 'OVERDUE')\n                AND returned_at IS NULL\n            )\n            ", name='ck_loans_status_return_consistency'),
    sa.CheckConstraint('due_at >= issued_at', name='ck_loans_due_after_issued'),
    sa.CheckConstraint('returned_at IS NULL OR returned_at >= issued_at', name='ck_loans_returned_after_issued'),
    sa.ForeignKeyConstraint(['copy_id'], ['book_copies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['librarian_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loans_copy_id', 'loans', ['copy_id'], unique=False)
    op.create_index('ix_loans_due_at', 'loans', ['due_at'], unique=False)
    op.create_index('ix_loans_librarian_id', 'loans', ['librarian_id'], unique=False)
    op.create_index('ix_loans_status', 'loans', ['status'], unique=False)
    op.create_index('ix_loans_user_id', 'loans', ['user_id'], unique=False)
    op.create_index('uq_loans_active_copy', 'loans', ['copy_id'], unique=True, postgresql_where=sa.text("status IN ('ACTIVE', 'OVERDUE')"))
    op.create_table('fines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('UNPAID', 'PAID', 'CANCELLED', name='fine_status'), server_default='UNPAID', nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'PAID'\n                AND paid_at IS NOT NULL\n            )\n            OR\n            (\n                status IN ('UNPAID', 'CANCELLED')\n                AND paid_at IS NULL\n            )\n            ", name='ck_fines_status_paid_consistency'),
    sa.CheckConstraint('amount > 0', name='ck_fines_amount_positive'),
    sa.CheckConstraint('paid_at IS NULL OR paid_at >= issued_at', name='ck_fines_paid_after_issued'),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fines_loan_id', 'fines', ['loan_id'], unique=False)
    op.create_index('ix_fines_status', 'fines', ['status'], unique=False)
    op.create_index('ix_fines_user_id', 'fines', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fines_user_id', table_name='fines')
    op.drop_index('ix_fines_status', table_name='fines')
    op.drop_index('ix_fines_loan_id', table_name='fines')
    op.drop_table('fines')
    op.drop_index('uq_loans_active_copy', table_name='loans', postgresql_where=sa.text("status IN ('ACTIVE', 'OVERDUE')"))
    op.drop_index('ix_loans_user_id', table_name='loans')
    op.drop_index('ix_loans_status', table_name='loans')
    op.drop_index('ix_loans_librarian_id', table_name='loans')
    op.drop_index('ix_loans_due_at', table_name='loans')
    op.drop_index('ix_loans_copy_id', table_name='loans')
    op.drop_table('loans')
    op.drop_index('ix_reservations_user_id', table_name='reservations')
    op.drop_index('ix_reservations_status', table_name='reservations')
    op.drop_index('ix_reservations_book_status_queue', table_name='reservations')
    op.drop_index('ix_reservations_book_id', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('ix_notifications_user_is_read', table_name='notifications')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('book_genres')
    op.drop_index('ix_book_copies_status', table_name='book_copies')
    op.drop_index('ix_book_copies_book_id', table_name='book_copies')
    op.drop_table('book_copies')
    op.drop_table('book_authors')
    op.drop_table('users')
    op.drop_table('genres')
    op.drop_table('books')
    op.drop_table('authors')
    # ### end Alembic commands ###
